CC=g++
CFLAGS= -ggdb -funsigned-char #-march=core2
LDFLAGS= -lc #-lxml2 -lz -lm -lpthread -lgcc_s -lssh2 -lssh -lssh_threads -lhiredis -lrt#-lefence
S_OBJECTS= sha1sum.o sha1.o recurse_dir.o md5.o gingko_base.o gingko_serv.o
SERVER= ../bin/gingko_serv
C_OBJECTS= sha1sum.o sha1.o recurse_dir.o md5.o gingko_base.o gingko_clnt.o
CLIENT= ../bin/gingko_clnt

all: lib client server

lib: libevent

libevent:
		cd ../lib/libevent && ./configure && make

server: clean $(SERVER)
		
client: clean $(CLIENT)

$(SERVER): $(S_OBJECTS)
		$(CC) $(CFLAGS) $(LDFLAGS) -o $(SERVER) $(S_OBJECTS)
		#rm -rf $(OBJECTS)

$(CLIENT): clean $(C_OBJECTS)
		$(CC) $(CFLAGS) $(LDFLAGS) -o $(CLIENT) $(C_OBJECTS)
		#rm -rf $(OBJECTS)

%.o: %.cc
		$(CC) $(CFLAGS) $(LDFLAGS) $^ -c -o $@

clean:
		rm -rf $(SERVER) $(S_OBJECTS) $(CLIENT) $(C_OBJECTS)
