/**
 * route.h
 *
 *  Created on: 2011-5-25
 *      Author: auxten
 **/

#ifndef ROUTE_H_
#define ROUTE_H_

/// get the possible block source, src_max in max
int get_blk_src(s_job_t * jo, unsigned src_max, GKO_INT64 blk_idx,
        vector<s_host_t> * h_vec);
/// decide the final src from the host set generated by get_blk_src()
int decide_src(s_job_t * jo, int src_max, GKO_INT64 blk_idx,
        vector<s_host_t> * h_vec, s_host_t * h, char * buf);

#endif /** ROUTE_H_ **/
